apiVersion: apps/v1
kind: Deployment
metadata:
  name: king-desk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: king-desk
  template:
    metadata:
      labels:
        app: king-desk
    spec:
      containers:
      - image: kingma/ubuntu-xfce-vnc:latest
        name: king-desk                
        ports:
        - containerPort: 8080
        resources: 
          limits:
            memory: "4Gi"
            cpu: "2000m"

---

apiVersion: v1
kind: Service
metadata:
  name: king-desk
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "king-desk-port"
    port: 8080
  selector:
    app: king-desk
